server:
  port: ${PORT:9999}

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbit-service
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVICE_URL:localhost}:9411
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always

info:
  app:
    name: company-microservice
    description: This is the checkpoint 2 microservices architecture
    version: 1.0.0
  author: Thalles Denner
  mail: thalles@email.com

queue:
  movie-service: queue-movie-service
  series-service: queue-series-service

message: Test application.yml
